### ISSUE TITLE
Config.json is generating an error. 

### ISSUE THREAD

**Issue by mcfardo907** [Marlamin/wow.tools.local#2]
I changed the file location for my wow installation in "config.json," after I got An error.

" config.json reading, make sure it is valid. Application will be unable to load correctly. Error message: Failed to load configuration from file 'D:\Documents\Release-win-x64\config.json'."

The program will run because of it.

**Comment by Marlamin** [comment]
Make sure slashes are pointing the right way: /

**Comment by mcfardo907** [comment]
The slashed are going the right way. Does the folder for this program need to be in a specific directory? 
Here's the contents of config.json.
`{
  "config": {
    "definitionDir": "WoWDBDefs/definitions",
    "dbcFolder": "dbcs",
    "listfileURL": "https://github.com/wowdev/wow-listfile/raw/master/community-listfile.csv",
    "tactKeyURL": "https://github.com/wowdev/TACTKeys/raw/master/WoW.txt",
    "wowFolder": "C:/program files (x86)/battle.net/wow ",
    "wowProduct": "wow",
    "region": "eu",
    "locale": "enUS"
  }
}`

**Comment by Marlamin** [comment]
There's a space after the folder before the " so make sure that isn't there and if it's pointing to the folder that has a Data folder, a.build.info file and one or more subfolders like `_retail_` or `_ptr_` it should be fine.

**Comment by mcfardo907** [comment]
I got past that hurdle, now I am getting. `Exception initializing CASC: Access to the path 'D:\Documents\Release-win-x64 001\TactKey.csv' is denied.`

**Comment by Marlamin** [comment]
Not sure what to do about that, maybe something is blocking write access to that folder/file, try adding the folder as an exclusion to whatever virus scanner you're using.

**Comment by mcfardo907** [comment]
Thanks for your help. I am sure that this will get ironed out.

**Comment by Marlamin** [comment]
Let me know if you manage to get it working or not, worst case scenario I can add some debug statements or make it skip that part if it fails (although that will cause other issues down the line).

**Comment by mcfardo907** [comment]
I would like to figure out, why its denying access.

**Comment by Marlamin** [comment]
Try this

https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26.

**Comment by mcfardo907** [comment]
I changed the permission settings. Fixed the previous issue. I am getting this one now. 

`Unhandled exception. System.UnauthorizedAccessException: Access to the path 'D:\Documents\Release-win-x64 001\manifests\10.0.5.48526.txt' is denied.
`
I unclicked "read only," in the security settings, but checked it again, and it . I move the folder to another drive, will update and see if that is a fix or workaround.

**Comment by mcfardo907** [comment]
Transferring to the other drive fixed those errors, but now it's hanging after 
`info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Release-win-x64 001`
I let it run to see if it's something that takes a while. Got up this morning, and it's still hanging there.

**Comment by Marlamin** [comment]
It might just be done, see if there is a localhost URL mentioned that you can browse to in your browser (as readme says).

**Comment by mcfardo907** [comment]
> It might just be done, see if there is a localhost URL mentioned that you can browse to in your browser (as readme says).

I can browse it. Here's a screenshot.
![8cd283710d632771991d783e26591cd9](https://user-images.githubusercontent.com/32855814/225933261-9183cd95-69bc-4da7-bc3f-64ff67a93071.png)
 I'll go back to the instructions and see what I have to do next. Thank you again for helping me out.
