### ISSUE TITLE
Bug: type:ogg search shows mp3.

### ISSUE THREAD

**Issue by YuvalAziza** [Marlamin/wow.tools.local#36]
Dear Marl,
Today, with the coming of the new classic era ptr, I stumbled upon something very strange in WTL. I wished to check ogg files, so I searched the following string: "Type:ogg." I was surprised to see the results were MP3 and ogg files, which confused me.

This behavior leads me to send you this bug report.
I will end with a note that the other way around won't show an ogg file in case I search type:mp3

**Comment by Marlamin** [comment]
Fixed in [51bfb1f](https://github.com/Marlamin/wow.tools.local/commit/51bfb1f7379c293f75d800fac5336c05bbdd902e)
